# Generated by Django 4.1.6 on 2023-03-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_hex_code_tag_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeToIngredient',
            new_name='RecipeIngredient',
        ),
    ]
